services:
  mc_atm7:
    image: itzg/minecraft-server
    container_name: minecraft-chaos
    ports:
      - 25565:25565
    restart: unless-stopped
    volumes:
      - ./modpacks:/modpacks:ro
      - data:/data
      # - ./mods.txt:/extras/mods.txt:ro
    stdin_open: true
    tty: true
    environment:
      EULA: "true"
      TYPE: MODRINTH
      MODRINTH_MODPACK: https://modrinth.com/modpack/cobblemon-fabric/version/1.3.2
      VERSION: 1.21.4
      # CF_SERVER_MOD: /modpacks/ServerFiles-2.41.zip
      MEMORY: "24G"
      ENABLE_ROLLING_LOGS: "true"
      TZ: "America/Chicago"
      OVERRIDE_SERVER_PROPERTIES: "true"
      DIFFICULTY: "easy"
      MAX_TICK_TIME: "-1"
      ALLOW_FLIGHT: "true"
      OPS: ""
      VIEW_DISTANCE: 32
      MAX_PLAYERS: 20
      PVP: "true"
      LEVEL_TYPE: "biomesoplenty"
      MOTD: "Good luck"
      # MODS_FILE: /extras/mods.txt
      # REMOVE_OLD_MODS: "true"

volumes:
  data: